// Generated by ReScript, PLEASE EDIT WITH CARE


function makeParam(type_, description) {
  return {
    type: type_,
    description: description
  };
}

function stringParam(description) {
  return {
    type: "string",
    description: description
  };
}

function numberParam(description) {
  return {
    type: "number",
    description: description
  };
}

function boolParam(description) {
  return {
    type: "boolean",
    description: description
  };
}

export {
  makeParam,
  stringParam,
  numberParam,
  boolParam,
}
/* No side effect */
