// Generated by ReScript, PLEASE EDIT WITH CARE


async function checkBinaryExists(binary) {
  try {
    ((new Deno.Command("which", { args: [binary], stdout: "piped", stderr: "piped" })));
    await (cmd.output());
    let code = output.code;
    return code === 0;
  } catch (exn) {
    return false;
  }
}

async function executeCommand(binary, args) {
  ((new Deno.Command(binary, { args: args, stdout: "piped", stderr: "piped" })));
  await (cmd.output());
  let decoder = new TextDecoder();
  let stdout = output.stdout;
  let stderr = output.stderr;
  let code = output.code;
  return {
    stdout: decoder.decode(stdout),
    stderr: decoder.decode(stderr),
    code: code
  };
}

function getEnvOr(key, $$default) {
  let value = Deno["env.get"](key);
  if (value !== undefined) {
    return value;
  } else {
    return $$default;
  }
}

export {
  checkBinaryExists,
  executeCommand,
  getEnvOr,
}
/* No side effect */
